### ISSUE TITLE
Introducing our paper OccMamba and OccRWKV

### ISSUE THREAD

**Issue by jmwang0117** [Event-AHU/Mamba_State_Space_Model_Paper_List#11]
Thank you for your excellent work!

Can you add our two papers to the survey or README?

1. OccMamba: https://arxiv.org/abs/2408.10618

2. OccRWKV: https://arxiv.org/abs/2409.19987

**Comment by wangxiao5791509** [comment]
@jmwang0117  Hi, the two papers have been updated in the readme.
