### ISSUE TITLE
Adding a new SSM paper for RecSys

### ISSUE THREAD

**Issue by Yueeeeeeee** [Event-AHU/Mamba_State_Space_Model_Paper_List#5]
Hi,

Thank you for this awesome repo of state space models! We recently release our WSDM 2024 paper called LRURec, which uses linear recurrence and parallel scan for efficient training & inference in sequential recommendation. The paper can be found at https://arxiv.org/abs/2310.02367 and the code is available at: https://github.com/yueqirex/LRURec

Would you mind adding this work to the repo and survey as well? Thank you!

**Comment by wangxiao5791509** [comment]
@Yueeeeeeee  Thanks for your attention on this survey. We will update this work ASAP.

**Comment by Yueeeeeeee** [comment]
That'd be great, and thank you for the prompt response!
