### ISSUE TITLE
Wrong reference

### ISSUE THREAD

**Issue by skeletondyh** [Event-AHU/Mamba_State_Space_Model_Paper_List#6]
Dear authors,

Congrats on the great survey and thank you for citing our paper GRED!

But it seems the reference to GRED in the survey is wrong (e.g., in section 3.4 page 15, and Table 1), which mistakenly coincides with Graph Mamba

We would appreciate it if this could be corrected. Thanks!

**Comment by wangxiao5791509** [comment]
@skeletondyh  Thanks for your kind reminder. We will correct this issue ASAP.
